### ISSUE TITLE
Ability to give event dragons?

### ISSUE THREAD

**Issue by thenaptaker** [DinoDevs/Everwing-Hacks#1]
Would be nice to be able to acquire the Sphinx dragons that seem to only be available from the daily mission.

**Comment by GramThanos** [comment]
The events are running only for a limited time, that's why we have no codes for them.
But you can easily get, for example, a sidekick from the "Sphinx Challenge" by running the command

```javascript
GC.app.client.runFunction("sidekickEventGacha", {eventID : "sphinxChallenge"});`
```

Or you can get a random sidekick from the events listed ingame at the moment
```javascript
var events = GC.app.client.schemaAPI.getTable("sidekicksEvents").rows;
var sidekickEvents = [];
for(var i = events.length - 1; i>=0; i--){
	if (events[i].sidekicks) sidekickEvents.push(events[i].name);
}
if(sidekickEvents.length > 0){
	GC.app.client.runFunction("sidekickEventGacha", {eventID : sidekickEvents[Math.floor(Math.random() * sidekickEvents.length)]});
}
else{console.log("No events.");}
```

**Comment by thenaptaker** [comment]
It seems that Pharocious isn't it the sphinxChallenge table, is there a way to create a function that opens the daily mission loot screen?

**Comment by GramThanos** [comment]
:P You are greedy :P ...
Ok I created for you my friend a super duper ultra function 👏 to get any sidekick you want.

I updated the readme with the function (get it from there) and you can run 
```javascript
getSidekickById("PC22");
```
to get your precious *Pharis*.

**Comment by thenaptaker** [comment]
Ahahahaha that made me laugh. I appreciate what you're able to do, thank you.
