### ISSUE TITLE
Can not use fake game

### ISSUE THREAD

**Issue by Neblara** [DinoDevs/Everwing-Hacks#10]
I can not really understand where to write fakegame coin 10000.

**Comment by Chikinexe** [comment]
You have a detailed guide with images here: https://github.com/DinoDevs/Everwing-Hacks/blob/master/docs/guide.md
Follow the guide and paste the code of "Fake a Game run" there:
`var playFakeGame = function(data) {
	// Fake game data
	var data = data || {};
	data.score = data.score || 10 + Math.round(Math.random()*10);
	data.seconds = data.seconds || 10 + Math.round(Math.random()*10);
	data.coins = data.coins || 0;
	data.trophies = data.trophies || 0;
	data.energy = data.energy || 0;
	data.xp = data.xp || 0;
	data.sidekick_xp = data.sidekick_xp || 0;
	// Get sidekicks
	var sidekicks = {};
	var sidekicks_db = window.GC.app.gameView.sidekicksModel.sidekicksList;
	for(var i=0; i<sidekicks_db.length; i++){
		if(sidekicks_db[i].state == "equippedLeft"){sidekicks.left = sidekicks_db[i];}
		else if(sidekicks_db[i].state == "equippedRight"){sidekicks.right = sidekicks_db[i];}
	}
	// App reference
	var app = window.GC.app;
	// Send command
	app.mvc.commandMap.GamePlayedCommand.prototype.execute.apply({mvc :app.mvc,finishCommand : function(e, $){}},
	[{
		playerID : app.gameModel.player.id,
		secondsElapsed : data.seconds,
		killedBy : "Meteor SINGLE " + (Math.round(Math.random()*3) + 1),
		background : "ocean",
		score : data.score,
		commonEarned : data.coins,
		premiumEarned : data.trophies,
		energyEarned : data.energy,
		playerXP : data.xp,
		sidekickXP : data.sidekick_xp,
		sidekickLeftID : (sidekicks.left) ? sidekicks.left.id : null,
		sidekickRightID : (sidekicks.right) ? sidekicks.right.id : null,
	}]);
}`
After that, press enter, then you type 
`playFakeGame({coins : 15000});`
in the textbar, the same one you inserted the "Fake a Game Run"

**Comment by Chikinexe** [comment]
It didn't came out as I wanted to, so you go on the site above and follow the guide to go to the developers tools and there paste the code "Fake a Game Run", press enter, then paste the command : playFakeGame({coins : 15000});
