### ISSUE TITLE
How to get the Mythic Lethio Sidekick?

### ISSUE THREAD

**Issue by ZataraTMM** [DinoDevs/Everwing-Hacks#12]
The code for the Lethio sidekick is the old one, it says legendary [legacy], is there some special thing i need to do to get the Mythic ones thro the codes?

**Comment by GramThanos** [comment]
Do you mean `SC13` ?

**Comment by GramThanos** [comment]
I updated the sidekicks codes.

[Commit 7b9a683bcc243bed687e3617f5796cc9f4bd9019]
