### ISSUE TITLE
"Get any sidekick you want" not working anymore

### ISSUE THREAD

**Issue by tbrgh** [DinoDevs/Everwing-Hacks#15]
Looks like they patched it...?

> WARN	 Ledger:1:everwing 	|  disposer rejection: 
Error
columnNumber: 216586
fileName: "https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/bootstrap.js line 1 > eval"
lineNumber: 229
message: "No listingFunction registered for name: \"sidekickEventGacha\""
stack: "M</SchemaAPI.prototype.getFunction@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/bootstrap.js line 1 > eval:229:216586\ng</DispatchContext.prototype.runFunction/<@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/bootstrap.js line 1 > eval:136:114319\ntryCatcher@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:79016\n[22]</r.exports/Promise.prototype._settlePromiseFromHandler@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:49808\n[22]</r.exports/Promise.prototype._settlePromise@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:50646\n[22]</r.exports/Promise.prototype._settlePromiseCtx@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:51184\n[2]</Async.prototype._drainQueue@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:2966\n[2]</Async.prototype._drainQueues@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:3045\nAsync/this.drainQueues@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:992\n"
__proto__: Object { … }
bootstrap.js%20line%201%20%3E%20eval:31:26019

> Error during stormcloud game state dispatch: 
Error
columnNumber: 216586
fileName: "https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/bootstrap.js line 1 > eval"
lineNumber: 229
message: "No listingFunction registered for name: \"sidekickEventGacha\""
stack: "M</SchemaAPI.prototype.getFunction@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/bootstrap.js line 1 > eval:229:216586\ng</DispatchContext.prototype.runFunction/<@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/bootstrap.js line 1 > eval:136:114319\ntryCatcher@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:79016\n[22]</r.exports/Promise.prototype._settlePromiseFromHandler@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:49808\n[22]</r.exports/Promise.prototype._settlePromise@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:50646\n[22]</r.exports/Promise.prototype._settlePromiseCtx@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:51184\n[2]</Async.prototype._drainQueue@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:2966\n[2]</Async.prototype._drainQueues@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:3045\nAsync/this.drainQueues@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:992\n"
__proto__: Object { … }
bootstrap.js%20line%201%20%3E%20eval:1:48630

> Unhandled rejection M</SchemaAPI.prototype.getFunction@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/bootstrap.js line 1 > eval:229:216586
g</DispatchContext.prototype.runFunction/<@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/bootstrap.js line 1 > eval:136:114319
tryCatcher@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:79016
[22]</r.exports/Promise.prototype._settlePromiseFromHandler@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:49808
[22]</r.exports/Promise.prototype._settlePromise@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:50646
[22]</r.exports/Promise.prototype._settlePromiseCtx@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:51184
[2]</Async.prototype._drainQueue@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:2966
[2]</Async.prototype._drainQueues@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:3045
Async/this.drainQueues@https://apps-141184676316522.apps.fbsbx.com/instant-bundle/1174389249249108/1578800175503239/node_thirdParty.chunk.js:25:992

**Comment by hanhcom** [comment]
not working for me either.

**Comment by GramThanos** [comment]
I will check it as soon I found some time.

**Comment by GramThanos** [comment]
Yes, a function was removed from the game's code, so we will have to find an other way around.

For now, I removed this code from the readme
b36bd346cb3c09ade31625b330f7d48744292093

**Comment by hanhcom** [comment]
Thank you.  Im waiting for another solution.

**Comment by GramThanos** [comment]
New code added.
Commit 4a6fde22a4a5f2edbf0eb7626863c088c6be098f
