### ISSUE TITLE
Random Event sidekick

### ISSUE THREAD

**Issue by Valiad** [DinoDevs/Everwing-Hacks#16]
Get a random event sidekick code is not working anymore.

**Comment by hoanghongkhang** [comment]
use
`GC.app.client.runFunction("sidekickGacha", {isFree : true, gachaType : "pegasus"});`
or 
`GC.app.client.runFunction("sidekickGacha", {isFree : true, gachaType : "pegasusPremium"});`
instead

**Comment by GramThanos** [comment]
Or to get a random:

```javascript
var gacha = GC.app.client.schemaAPI.getTable("gachaConfig").rows;
GC.app.client.runFunction("sidekickGacha", {isFree : true, gachaType : gacha[Math.floor(Math.random() * gacha.length)].type});
```
