### ISSUE TITLE
GC is not defined error

### ISSUE THREAD

**Issue by cjkim1995** [DinoDevs/Everwing-Hacks#2]
I think they recently patched this, I'm getting the following:

> Uncaught ReferenceError: GC is not defined
>     at <anonymous>:3:3

and

> Uncaught TypeError: Cannot read property 'app' of undefined
>     at playFakeGame (<anonymous>:13:31)
>     at <anonymous>:1:1

**Comment by GramThanos** [comment]
I don't think so. It works for me.

Did you selected the right page on the console?

> Click the down arrow next to the "top"
> On the drop down, sellect "index.html" (it should be on the bottom)

**Comment by max0831** [comment]
I also got this problem

**Comment by GramThanos** [comment]
The error you are talking about is displayed when you are applying the hacks on the wrong context window. So I created a detailed guide for you.

Please follow it carefully and comment below if this solved your errors.
https://github.com/DinoDevs/Everwing-Hacks/blob/master/docs/guide.md

**Comment by max0831** [comment]
done thx
