### ISSUE TITLE
set & forget

### ISSUE THREAD

**Issue by ensemblebd** [DinoDevs/Everwing-Hacks#20]
```
window.GC.app.gameView.model.boostersModel.boosters.magicBurst.cost=1;window.GC.app.gameView.model.boostersModel.boosters.magicBurst.perGameLimit=12;window.GC.app.gameView.model.boostersModel.boosters.relayTotem.cost=1;
window.GC.app.gameView.model.items.spawnChances.doubleShot=0.5;
```
A chrome plugin with hotkeys might be a worthwhile venture.

**Comment by ensemblebd** [comment]
Or just this and call it a day...

`window.GC.app.gameView.player.model.shootTimeout=1;`

**Comment by GramThanos** [comment]
We had a plug in, but users abused it by joining groups and instant killing the bosses. Also the game started looking for the extension and closed if found it.

**Comment by ensemblebd** [comment]
ahh then in that case, quite happy with this as it is :)
Dang didn't realize it got that bad, i just started this a week ago.

**Comment by GramThanos** [comment]
If we ever release one again, game play hack will not work on groups ta all.
