### ISSUE TITLE
How use Sidekicks code?

### ISSUE THREAD

**Issue by UrobroS** [DinoDevs/Everwing-Hacks#21]
HI. Im completly green, how should i edite this:
// Change this code
var sidekicks = {
	...
	"cha" : {
		names : {
			tier0 : "Charmander",
			tier1 : "Charmeleon",
			tier2 : "Charizard"
		}
	},
	...
};

// This will print them nice
var sidekickcodes_md = "", names;
for(var i in sidekicks){
	names = sidekicks[i].names;
	sidekickcodes_md += " - **" + i + "** : " + names.tier0 + ", " + names.tier1 + ", " + names.tier2 + "\n";
}
console.log(sidekickcodes_md);

to get this dragon: LC39 : Max, Maxus, Maximilian

Please help, bye :).

**Comment by GramThanos** [comment]
This is only a code that prints the game's sidekicks.

There is currently no hack code in this project to get a specific sidekick.

**Comment by werneckbh** [comment]
To get any sidekick you want, pause the VM and enter the following code in the console:

```javascript
sidekick = 'NC40' //change NC40 to any id
GC.app.mvc.sendNotification("ClaimCollectionRewardCommand", {sidekickID: sidekick+'...'})
```

**Comment by UrobroS** [comment]
@GramThanos so how can i print my dragon?

**Comment by GramThanos** [comment]
@UrobroS there is a nice tutorial [here](http://www.instructables.com/id/3D-Printing-a-Dragon/)
@werneckbh I will try it :P

**Comment by GramThanos** [comment]
New added for getting sidekicks
Commit 4a6fde22a4a5f2edbf0eb7626863c088c6be098f
