### ISSUE TITLE
How to have more damage in Boos Raids.?

### ISSUE THREAD

**Issue by cswl** [DinoDevs/Everwing-Hacks#22]
Some boss take very long to do..
Would be nice to have damage hack for bosses too..

**Comment by GramThanos** [comment]
Too much trouble for little gain...

**Comment by cswl** [comment]
Yeah I noticed that too.. 
Doesnt give much Rewards.. in terms of Gold coins..

I'm changing the question.. as I have another one..
How to have more damage in Boos Raids..

**Comment by GramThanos** [comment]
Your player's damage can be altered by by 3 factors.

Your bullet level can affect it, your attack speed and ofcourse your player damage.

So you can patch these 3 values... 
ex. `window.GC.app.gameModel.player.bulletLevel = 10;`

I could give you a fully working code of how to use them BUT people used to take my cheats and clear public bosses on messenger Everwing groups just to show off to other people that play the game fair.
I don't like this so I try not to release codes that may lure them to such bad habits again.

If you try you can find what you want, I gave you enough info :P
