### ISSUE TITLE
Copied Extention

### ISSUE THREAD

**Issue by ZataraTMM** [DinoDevs/Everwing-Hacks#25]
I don't know if you have noticed this, it seems way too familiar to your extension. I checked the source of it and there are traces of your team name.  **[[Moderator removed "pro-everwing-hack" link]](#)** here it is. I just wanted to let you know in case you guys didn't.

**Comment by GramThanos** [comment]
We know. This guy has copied all our code, removed the copyrights (some of them) and edited the css files. I think its a copy from a previous version.

The group restrictions were added for a reason. Even if the groups size is too low (as in your case) it solved the problem.

We haven't done anything to take it down as we think that this guy does not worth our time.
The cheats are all available on this github with examples, so he could just make his own extension using the public cheats codes, but we can not code, so he chose to steal our code...

**Comment by ZataraTMM** [comment]
I understand, i didn't use that one. I edited it myself. Now i'm trying to figure out how to add my own scripts and stuff. I wouldn't release this. is there no way for you to report him on the  chrome store?

**Comment by GramThanos** [comment]
I suppose there is a way. Personaly, I don't realy care.
