### ISSUE TITLE
Extension in Chrome was remove.

### ISSUE THREAD

**Issue by Ljfe** [DinoDevs/Everwing-Hacks#26]
I not found Extension in Chrome Store

**Comment by GramThanos** [comment]
I know.

If you really want to install it, workaround:

You can get it here
https://github.com/DinoDevs/Everwing-Hacks/releases/download/v2.1.1/EverWingHacks.v2.1.1.crx

And install it as a developer
https://stackoverflow.com/questions/24577024/install-chrome-extension-not-in-the-store

**Comment by Ljfe** [comment]
Cảm ơn bạn rất nhiều.
*Lê Hiếu*
*Liên hệ: www.facebook.com/lehiieu <http://www.facebook.com/lehiieu>*


Vào Th 5, 20 thg 9, 2018 vào lúc 22:18 Grammatopoulos
Athanasios-Vasileios <notifications@github.com> đã viết:

**Comment by MusicInMe** [comment]
Hi,
any chance for an update?  Ext works only when applying in-game hacks.  
Thanks anyway, was really fun to get some extra coins ;)

**Comment by GramThanos** [comment]
It is not currently in my plans.
