### ISSUE TITLE
Found code for Pigmalion

### ISSUE THREAD

**Issue by Acies33** [DinoDevs/Everwing-Hacks#29]
Hello! I don't know if this was intended or not but there's no code for pigmalion on the sidekick list, I found it. Can I post it?

**Comment by GreatApo** [comment]
Be my guest 👍

**Comment by GramThanos** [comment]
I added the missing sidekicks!
Thanks for the information that there were missing sidekicks.

PC03 : Pigmalion, Pigmalionus, Pigesquire
WC43 : Volt, Lantis, Voltantis

If you found a different code please inform us.

**Comment by Acies33** [comment]
Ay you beat me to it, it was PC03

**Comment by Acies33** [comment]
Found some extra codes too, like this one for the fake game to earn energy:
playFakeGame({energy : 15});

And the fourth parameter to generate sidekick, true for perfect zodiac, false for normal.

**Comment by Acies33** [comment]
Yes, of course, but some people don't know how to do it themselves that's why I said it, same with the pigmalion, a bit of common sense you can guess the code but if you don't understand the code at all...

**Comment by GramThanos** [comment]
Well this repository was created for people that understand some programming (as it is stated in the readme file).

Probably there is a way to get Gems as the hole game has no security and no protection over script injections. It is not in my interest to hack the gem system.

**Comment by Acies33** [comment]
Thought Gems were somehow more protected than the rest since they are newer and you have to pay for them. I agree it's kind of pointless getting gems since you can have anything you want with the codes you provided but I'd like to try.
