### ISSUE TITLE
Uncaught TypeError when trying to use playfakegame

### ISSUE THREAD

**Issue by Synaps33** [DinoDevs/Everwing-Hacks#31]
Web Browser: Opera
OS: WIndows 8 64Bit
I just cant execuute any of those play fake game after executing code for playfakegame.

![przechwytywanie](https://user-images.githubusercontent.com/22098377/52522233-a9580780-2c82-11e9-9440-13fad8835107.PNG)

**Comment by GramThanos** [comment]
Game patched it.
