### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by ZataraTMM** [DinoDevs/Everwing-Hacks#35]
Could i get in contact of any of the devs of this for some slight push in the right direction? I'm not asking to be spoonfed, just want to figure something out.

**Comment by GramThanos** [comment]
You can send me anything you like at gramthanos@gmail.com

**Comment by ZataraTMM** [comment]
> You can send me anything you like at [gramthanos@gmail.com](mailto:gramthanos@gmail.com)

Thank you. I sent you an email.
