### ISSUE TITLE
Extention

### ISSUE THREAD

**Issue by ZataraTMM** [DinoDevs/Everwing-Hacks#36]
Am i allowed to pickup this project? Ofc, all credits will be still there and everything related. I just need help with changing some stuff as i'm getting errors, if not, i'll just keep the update to myself. I just need help with some stuff.

**Comment by GramThanos** [comment]
The extension's code is not online thus it is not open sourced. I didn't had time to finish and release the next version. Maybe I will have to release an alpha with some fixes and some parts turned off.

**Comment by ZataraTMM** [comment]
> The extension's code is not online thus it is not open sourced. I didn't had time to finish and release the next version. Maybe I will have to release an alpha with some fixes and some parts turned off.

Ah okay. Because i was working on one for our discord group. sence the discord group is public, i'll not publish it. I did change some stuff around and gonna clean up some stuff, i'll keep it for myself and respect your choice.

**Comment by GramThanos** [comment]
Version 2.1.6 is out.
