### ISSUE TITLE
Issue spam, sorry. Weapon Function.

### ISSUE THREAD

**Issue by ZataraTMM** [DinoDevs/Everwing-Hacks#37]
I'm sorry for the issure spam. Just want to get this to work. 

[I get this error when i try to enable this hack](https://i.imgur.com/nQXAYEE.png)
[And this](https://i.imgur.com/OUphYGE.png)

Yes, i've done everything right. the hack enables, etc, but it doesn't seem to change the speed.

`			weapon : {
				// Manage
				name : 'hacks.weapon',
				active : false,
				// Variables
				speed : 5,
				// Tick inject
				tick : function() {
					if(this.active){
							window.GC.app.gameModel.player.shootTimeout = 64 - this.speed;
					}
				}
			},`

I edited it like this. i tried with -1, etc, the way it was, nothing seemed to edit the actual speed and i get that error. Any help?

**Comment by GramThanos** [comment]
The error indicates that you pasted something weird there, or the line error is wrong.

**Comment by ZataraTMM** [comment]
> The error indicates that you pasted something weird there, or the line error is wrong.

I think it's wrong sence it works fine. It just simply doesn't edit the shoottimeout though, no matter what i edit in it.

**Comment by GramThanos** [comment]
Maybe what is disabled should remain disabled :P

**Comment by ZataraTMM** [comment]
> Maybe what is disabled should remain disabled :P

*big puppy eyes* pretty please? last thing :3 i ask for. I managed to change the throphies into diamodns for more coins, etc, etc. but this is really bugging me!

**Comment by GramThanos** [comment]
Change speed from 5 to 64

**Comment by ZataraTMM** [comment]
> Change speed from 5 to 64

Still the same. No change in my speed

`			weapon : {
				// Manage
				name : 'hacks.weapon',
				active : false,
				// Variables
				speed : 64,
				// Tick inject
				tick : function() {
					if(this.active){
							window.GC.app.gameModel.player.shootTimeout = 101 - this.speed;
					}
				}
			},`

not even a slight change, for it to be 64 *that's the normal for my jade char* doesn't put it to 101 either. i tried swapping them no luck

**Comment by GramThanos** [comment]
Then you haven't enabled it correctly.

**Comment by ZataraTMM** [comment]
`	// Handlers
	EverWingHacks.magnet = function(){
		conn.fire("magnet");
	}
	EverWingHacks.doubleshot = function(){
		conn.fire("doubleshot");
	}
	EverWingHacks.rush = function(){
		conn.fire("rush");
	}
	EverWingHacks.nometeors = function(){
		conn.fire("nometeors");
	}
	EverWingHacks.timescale = function(){
		conn.fire("timescale");
	}
	EverWingHacks.wavespacing = function(){
		conn.fire("wavespacing");
	}
	EverWingHacks.lootweights = function(){
		conn.fire("lootweights");
	}
		**EverWingHacks.weapon = function(){
		conn.fire("weapon");**
	}
	
	
	conn.on("magnet", function(data){
		cache.magnet = data.active;
		updateBackpage();
	});
	conn.on("doubleshot", function(data){
		cache.doubleshot = data.active;
		updateBackpage();
	});
	conn.on("rush", function(data){
		cache.rush = data.active;
		updateBackpage();
	});
	conn.on("nometeors", function(data){
		cache.nometeors = data.active;
		updateBackpage();
	});
	conn.on("timescale", function(data){
		cache.timescale = data.active;
		updateBackpage();
	});
	conn.on("wavespacing", function(data){
		cache.wavespacing = data.active;
		updateBackpage();
	});
	conn.on("lootweights", function(data){
		cache.lootweights = data.active;
		updateBackpage();
	});
	**conn.on("weapon", function(data){
		cache.weapon = data.active;
		updateBackpage();**
	});
	`
injector.js^

`						<div class="option-wrapper" id="weapon">
							<div class="icon weapon-off"></div>
							<div class="option-item option-button">
								<div class="button">Toggle</div>
							</div>
							Weapon Speed
						</div>

popup.html ^



`		this.data['weapon'].el.textContent = (data['weapon']?'ON':'OFF');
		this.data['weapon'].el.className = 'button' + (data['weapon']?' active':''); `
popup.js^ 



`	});
	conn.on("weapon", function(data){
		logger("weapon : ", !EverWingHacks.hacks.weapon.active);
		EverWingHacks.hacks.weapon.active = !EverWingHacks.hacks.weapon.active;
		conn.fire("weapon", {active : EverWingHacks.hacks.weapon.active});
	});`

`				// Weapon hack
				this.hacks.weapon.tick(); `

`				this.weapon.self			= self;
				this.weapon.tools			= this.tools; `

`			weapon : {
				// Manage
				name : 'hacks.weapon',
				active : false,
				// Variables
				speed : 64,
				// Tick inject
				tick : function() {
					if(this.active){
						if(this.speed >= 0)
							window.GC.app.gameModel.player.shootTimeout = 101 - this.speed;
					}
				}
			},`

script.js ^

Hmm...?


`

**Comment by ZataraTMM** [comment]
Well putting them in code warps kidna effed them up but..yeah
