### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by RickyGeo** [DinoDevs/Everwing-Hacks#38]
Doesnt work

**Comment by GramThanos** [comment]
Does work.

**Comment by GramThanos** [comment]
Keep in mind that the hacks do not work if you are in a group!

When the hacks are all active, there is an "unlmited" indicator on the status.
![image](https://user-images.githubusercontent.com/14858959/56303575-de7e4b80-6144-11e9-9a08-9bca563d5b12.png)
