### ISSUE TITLE
Artificial limiting of coins able to be earned in game

### ISSUE THREAD

**Issue by SquaredDog** [DinoDevs/Everwing-Hacks#40]
Are the number of coins able to be earned in-game capped to a certain timeframe? When I set the loot weight to only spawn rubies, it causes an error code: 2 message, and forces the game to reload.

**Comment by SquaredDog** [comment]
Also occurs if I try to change the number of seconds before one of the resource hacks is activated, or if I try to force them to add more coins.

**Comment by SquaredDog** [comment]
Also, is there a way to activate fake games from within the extension?

**Comment by GramThanos** [comment]
It seems that all resources have a limit depending on the duration of the game run. You can access all the hacks from the console if you enable developer mode (click many times the year on the about page) then expose the hacks variable.
