### ISSUE TITLE
Can't unlock characters : disposer rejection

### ISSUE THREAD

**Issue by miaoxxx** [DinoDevs/Everwing-Hacks#5]
This does not work for me. I got error "WARN	Ledger:1:everwing	|  disposer rejection: Error: No listingFunction registered for name: "unlockCharacter"

Maybe they patched it?

**Comment by GramThanos** [comment]
This does not work for me too.
I will resolve it when I have time.

**Comment by Zudoku** [comment]
I found a solution to this. Just change the line 

`GC.app.client.runFunction("unlockCharacter",{characterName: names[i], isFree: true});`

to 

`GC.app.client.runFunction("purchaseCharacter", {
                characterID: names[i],
                isFree: !0
            });`

**Comment by GramThanos** [comment]
Thanks for the fix.
I can not verify if it works as I have all chars unlocked, but it does not throw an error.

Merged on commit db593141546218251d7c26de12fd2cfc11fa6f7c
