### ISSUE TITLE
6 new Halloween Dragon code

### ISSUE THREAD

**Issue by teuquy229** [DinoDevs/Everwing-Hacks#6]
-SC29: Magi, Magus, Sorceros 
-SC28: Ven, Venum, Venumarius 
-FC28: Lava, Magma, Vulcan 
-WC28: Icee, Fria, Frigidus 
-NC28: Lumi, Lucerna, Lumina 
-LC28: Cony, Chrysos, Cornelius

**Comment by GramThanos** [comment]
The codes where added to the list. Thank you.
Commit 3644ed67e82e9a616830077582689d8650f277f0
